Discordモデルの定義を移動
kaiyu-tech/stampon pull request #137
Opened 2021-12-04 09:02 UTC by kaiyu-tech

2021-12-05 20:23 UTC, komagata requested changes
Discordの機能がUtils的なクラスメソッドの集合になっているので、Discordクラスにふさわしいようにオブジェクト指向的に設計するのがいいかもです〜。

2021-12-06 11:00 UTC, kaiyu-tech commented
@komagata
ひとまずモデル内でしか使用しないメソッドをPrivateに変更しました。
Discordモデルはヘルパー的なイメージで作成したため、「Discordクラスにふさわしい」という指摘がピンと来ず、理解できていません💦

例えばどの部分をどの様に修正することを意味しているのかご教示いただけないでしょうか？🙇‍♂️

2021-12-07 19:39 UTC, komagata commented
@kaiyu-tech 

> Discordモデルはヘルパー的なイメージで作成したため、

極力ヘルパー的に作らずモデルを設計した方がいいかもという意味です〜

2021-12-07 20:40 UTC, kaiyu-tech commented
@komagata 
本機能はクラス変数やインスタンス変数が不要なため、Utils的なクラスメソッドの集合にするのが最適解だと、私は思っています。そのため「Discordクラスにふさわしい」が全くイメージできていません。

お手数おかけして申し訳ないのですが、「Discordクラスにふさわしい」とは具体的にどのようにコーディングすることを指しているのか、具体例でご教示いただきたいです🙇‍♂️

2021-12-08 14:43 UTC, komagata commented
@kaiyu-tech 

> 本機能はクラス変数やインスタンス変数が不要なため、Utils的なクラスメソッドの集合にするのが最適解だと、私は思っています。

なるほどです、僕も絶対ヘルパー的じゃない方がいいとは思わないのでこちらで大丈夫です〜。

2021-12-08 22:54 UTC, kaiyu-tech commented
@komagata
レビューありがとうございます🙏
今後機能が増えるなどで肥大化した場合はクラス化も検討させていただこうと思います。

2022-01-07 05:38 UTC, merged